fizzbuzz問題を作成しました。レビューをお願い致します。
oyuuuhan00/ruby-practices pull request #1
Opened 2024-12-07 22:57 UTC by oyuuuhan00

2024-12-12 09:24 UTC, u1tnk requested changes

2024-12-12 09:24 UTC, u1tnk commented on 01.fizzbuzz/fizzbuzz.rb
> +  x = 20
このxは何の変数かわからないので良くないです。
ここは分かりやすい名前の定数に入れましょう。

2024-12-12 09:24 UTC, u1tnk commented on 01.fizzbuzz/fizzbuzz.rb
> +  array = (1..x).to_a
arrayという変数は配列であることしか分からないので変数名は中身が何なのか分かるようにしましょう。
ただし、ここは変数にする必要はなく、 `to_a` する必要もなく `(1..x).each` で良いですね。

2024-12-13 01:37 UTC, oyuuuhan00 commented on 01.fizzbuzz/fizzbuzz.rb
> +  x = 20
ご指摘ありがとうございます。
X → number に変更しました！

2024-12-13 01:37 UTC, oyuuuhan00 commented on 01.fizzbuzz/fizzbuzz.rb
> +  array = (1..x).to_a
ご指摘ありがとうございます。
`(1..x).each`に修正しました！

2024-12-13 15:35 UTC, u1tnk commented on 01.fizzbuzz/fizzbuzz.rb
> +  x = 20
まず、変数では無く定数にしましょう。
ここだとNUMBERですね。

ただ、Xよりは良いですが、NUMBERも数字であることしか分かりません。

2024-12-22 13:11 UTC, oyuuuhan00 commented on 01.fizzbuzz/fizzbuzz.rb
> +  x = 20
変更することのない数が一箇所なのであれば変数に代入する必要はないという理解でよろしいでしょうか？
変数に入れるのをやめ、(1..20)に修正しました。

2024-12-24 14:16 UTC, merged